#!/usr/bin/env bash
# Install and configure HAProxy load balancer

apt-get update
apt-get -y install haproxy

echo "ENABLED=1" | tee /etc/default/haproxy

cat <<EOF >> /etc/haproxy/haproxy.cfg

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 3.82.176.167:80 check
    server web-02 98.94.20.97:80 check
EOF

service haproxy restart