#!/usr/bin/env bash
# Install nginx and serve Holberton School

apt-get update -y
apt-get install -y nginx

rm -f /var/www/html/index.nginx-debian.html

printf "Holberton School" > /var/www/html/index.html

systemctl restart nginx