#!/usr/bin/env bash

apt-get -y update
apt-get -y install nginx

echo "Ceci n'est pas une page" > /var/www/html/404.html

cat > /etc/nginx/sites-available/default <<'EOF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    error_page 404 /404.html;

    location = /404.html {
        internal;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
EOF

service nginx restart